	angular.module("storyModule",[])
	.config(function($stateProvider,$urlRouterProvider){
		$stateProvider
			.state('story',{
				url:'/story',
				templateUrl:'components/story/story.html',
				controller:'storycontrol',
				css:'components/story/story.css'
			})
	})
	.controller('storycontrol',['$scope','$http',function($scope,$http){
		$http.get('components/story/json/home.json').success(function(res){
			$scope.arr=res;
		})
	}])